### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by Erixonich** [POSAMN/clang#1]
Привет!
 
Во входном файле на первой строке число N и далее N строк на каждой 3 числа: X Y Z.

В выходном файле должно быть N строк, на каждой арифметическая прогрессия от X ... Y,  с разницей Z.

**Comment by POSAMN** [comment]
#include <stdio.h>
#include <stdlib.h>
/*
Во входном файле на первой строке число N и далее N строк на каждой 3 числа: X Y Z.
В выходном файле должно быть N строк, на каждой арифметическая прогрессия от X ... Y, с разницей Z.
*/

void addToFileArifmProgres(FILE* output, double start, double differ, double finish)
{
    while (start <= finish)
    {
        fprintf(output, "%lf ", start);
        start +=differ;
    }
    fprintf(output, "%c", '\n');
}

void addToFile(FILE* input, FILE* output)
{
    char kol = fgetc(input);
    double start;
    double differ;
    double finish;
    fgetc(input);
    for (int i = 0; i < 2; i++)
    {
    fscanf(input, "%lf", &start);
    printf("%lf", start);
    fscanf(input, "%lf", &differ);
    fscanf(input, "%lf", &finish);
    addToFileArifmProgres(output, start, differ, finish);
    printf("\n");
    }
}

int main(int argc, char** argv)
{
    if (argc > 4)
    {
        printf("error: can not gen information");
    }
    char* inputFileName = argv[1];
    char* outputFileName = argv[2];
    FILE* inputFile = fopen(inputFileName, "r");;
    FILE* outputFile = fopen(outputFileName, "w");
    if (outputFile == NULL)
    {
        printf("error: can not open file");
        return 7;
    }
    if (outputFile == NULL)
    {
        printf("error: can not file");
        return 5;
    }
    addToFile(inputFile, outputFile);
    fclose(inputFile);
    fclose(outputFile);
}
