### ISSUE TITLE
HW4-2

### ISSUE THREAD

**Issue by Erixonich** [POSAMN/clang#2]
входной файл: первая строка содержит число N и далее N строк, на каждой слово,  и символ X.
В выходном файле записать N слов в новой строке, исключив при этом все включения символа X из слова( если он присутствовал)

**Comment by POSAMN** [comment]
#include <stdio.h>
#include <stdlib.h>
/*
входной файл: первая строка содержит число N и далее N строк, на каждой слово, и символ X.
В выходном файле записать N слов в новой строке, исключив при этом все включения символа X из слова( если он присутствовал)
*/

void addInformationToFile(FILE* input, FILE* output)
{
    char c;
    char ch;
    c = fgetc(input);
    c = fgetc(input);
    if (c != 0 ) 
    {
        for (int i = 0; i < c; i++)
        {
            do
            {
                fscanf(input, "%c", &ch);
                if ((ch != 'x') && (ch != 'X') && (ch != '\n'))
                    fprintf(output, "%c", ch);
            }
            while (ch != '\n');
            fprintf(output, "%c", ' ');
        }
    }
}

int main(int argc, char** argv)
{
    if (argc > 3) printf("error: get infotmation");
    
    char* inputFileName = argv[1];
    FILE* inputFile =fopen(inputFileName, "r");
    if (inputFile == NULL) 
    {
        printf("error: can not open file");
        return 4;
    }
    char* outputFileName = argv[2];
    FILE* outputFile = fopen(outputFileName, "w");
    if (outputFile == NULL)
    {
        printf("error: can not open file");
        return 6;
    }
    addInformationToFile(inputFile, outputFile);
    
    fclose(inputFile);
    fclose(outputFile);
}
